### ISSUE TITLE
“Use const” suggested for lambda with quasi-quotes

### ISSUE THREAD

**Issue by dahlia** [ndmitchell/hlint#506] opened 2018-06-27 13:43 UTC
It's quite similar to #427, except hlint suggests “Use const” instead.  For example:

```
Suggestion: Use const
Found:
  \ x -> [shamlet|#{x}|]
Why not:
  const [shamlet|#{x}|]
```

**Comment by ndmitchell** [comment] 2018-06-29 14:52
Thanks for the report - I confirm that's a bug - I'll need to take quite a different approach to the previous bug though...

**Comment by ndmitchell** [comment] 2018-07-03 07:38
Dupe of https://github.com/ndmitchell/hlint/issues/483 so will use that to track it.

**Closed by ndmitchell** 2018-07-03 07:38 UTC
Labels: bug
