### ISSUE TITLE
Eta reduce suggested for variable used in quotation

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/hlint#427] opened 2018-01-23 13:08 UTC
Example code:

```hs
authOAuth2 name = authOAuth2Widget [whamlet|Login via #{name}|] name
```

And HLint (v2.0.11) doesn't see that `name` is used within the quotation, so it suggests *Eta reduce*, which would break the code.

I've just worked around it through `ignore`, but I thought it was worth reporting/documenting the behavior.

**Comment by ndmitchell** [comment] 2018-01-29 09:07
Thanks - much appreciated. The problem is I can't see inside a QuasiQuote, so don't know what it's doing, and have to be conservative. I'll fix this instance, but if you see any other instances, please let me know.

**Comment by ndmitchell** [comment] 2018-01-29 21:40
Fixed by just disabling the hint if a quasi quote is floating around.

**Closed by ndmitchell** 2018-01-29 21:41 UTC
