### ISSUE TITLE
Parse error: virtual }

### ISSUE THREAD

**Issue by wapxmas** [ndmitchell/hlint#241] opened 2016-05-31 19:04 UTC
```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module Main where

  import Yesod

  data App = App

  mkYesod "App" [parseRoutes|
  / HomeR GET
  |]

  instance Yesod App where

  getHomeR :: Handler Html
  getHomeR = defaultLayout $ do
    setTitle "toWidgetHead and toWidgetBody"
    toWidgetBody
      [hamlet|<script src=/included-in-body.js>|]
    toWidgetHead
      [hamlet|<script src=/included-in-head.js>|]

  main :: IO ()
  main = warp 3000 App

```

```
Parse error: virtual }
Found:
      main :: IO ()
      main = warp 3000 App
  > 

```

`**HLint v1.9.32, (C) Neil Mitchell 2006-2016**`

**Comment by wapxmas** [comment] 2016-05-31 19:07
On `HLint v1.9.33` same issue

**Comment by ndmitchell** [comment] 2016-06-01 08:05
Thanks for the report! This is a bug in the underlying haskell-src-exts library I use, which I've raised upstream with a simplified example at https://github.com/haskell-suite/haskell-src-exts/issues/310

As a matter of style, you almost never see people indent under the `module ... where` bit, so typically things like `import` and `instance` would always be in the left-most column. I expect that's what is making haskell-src-exts upset, because its a very untested corner.

**Comment by wapxmas** [comment] 2016-06-01 08:12
Thanks.

However next almost same source parsed without errors:

```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE TypeFamilies      #-}

module Main where

  import Yesod

  data Links = Links

  mkYesod "Links" [parseRoutes|
  / HomeR GET
  /page1 Page1R GET
  /page2 Page2R GET
  |]

  instance Yesod Links

  getHomeR :: Handler Html
  getHomeR = defaultLayout [whamlet|<a href=@{Page1R}>Go to page 1!</a>|]

  getPage1R :: Handler Html
  getPage1R = defaultLayout [whamlet|<a href=@{Page2R}>Go to page 2!</a>|]

  getPage2R :: Handler Html
  getPage2R = defaultLayout [whamlet|<a href=@{HomeR}>Go to home!</a>|]

  main :: IO ()
  main = warp 3000 Links

```

**Comment by ndmitchell** [comment] 2016-06-01 08:20
Yep, I expect an instance with a trailing where and no body causes the issue - it probably thinks the rest of the file should scope under the instance. A definite case of unintended interactions, but also definitely a bug.

**Comment by ndmitchell** [comment] 2020-03-15 20:37
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Closed by ndmitchell** 2020-03-15 20:37 UTC
Labels: depends-on-HSE
