### ISSUE TITLE
wrong suggestions in bidirectional pattern synonyms

### ISSUE THREAD

**Issue by divipp** [ndmitchell/hlint#212] opened 2016-01-25 08:26 UTC
Issue.hs:

```
{-# LANGUAGE PatternSynonyms #-}
pattern A <- (True, True) where A = (not $ False && True, True)
```

hlint suggestions:

```
Issue.hs:2:38: Error: Evaluate
Found:
  not $ False
Why not:
  True

Issue.hs:2:38: Warning: Redundant $
Found:
  not $ False
Why not:
  not False

2 suggestions
```

**Comment by ndmitchell** [comment] 2016-01-26 16:12
Thanks! Looks like something (either me or Haskell-Src-exts) is forgetting to fixity inside the pattern. Would it be legitimate for hlint to suggest evaluating the && and replace that with False?

**Comment by divipp** [comment] 2016-01-26 18:53
Yes, it would be legitimate to suggest evaluating (&&) here. Btw, this is not a real-life example, I simplified a more complex one and got this.

**Comment by ndmitchell** [comment] 2016-01-30 21:13
Thanks for the simplification. I think this is an error in the underlying HSE library, which I've raised upstream at https://github.com/haskell-suite/haskell-src-exts/issues/290.

**Comment by ndmitchell** [comment] 2020-03-15 20:50
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Closed by ndmitchell** 2020-03-15 20:50 UTC
Labels: depends-on-HSE
