### ISSUE TITLE
Error refactoring file from stdin

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#192] opened 2015-11-24 01:38 UTC
I get the following output when trying to refactor a file from stdin:

```
$ hlint - --refactor < MyFile.hs
hlint: <stdin>: hSetBuffering: illegal operation (handle is closed)
refactor: /run/user/1000/extra-file-4084039286-1804289383846930886: getFileStatus: does not exist (No such file or directory)
```

This happens regardless of the contents of MyFile.hs.
I'm using HEAD of both refactor and hlint.

```
$ uname -a
Linux risa 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 GNU/Linux
$ hlint --version
HLint v1.9.24, (C) Neil Mitchell 2006-2015
$ refactor --version
v0.1.0.0
```

Please let me know if there's any further information I can provide.

**Comment by ndmitchell** [comment] 2015-11-24 08:48
@mpickering I'm not really sure what this is meant to do. As a test, I ran `hlint Sample.hs --refactor`, and it just broked the Sample.hs file with the list of hints.

**Comment by mpickering** [comment] 2015-11-24 09:35
I can't reproduce this locally. Can you both please provide some more information about your systems?

```

**Comment by mpickering** [comment] 2015-11-24 09:36
I can't reproduce this easily. Can you please provide some more information about your systems?

```
~/Documents/haskell:cat sample.hs 

foo = (x)
~/Documents/haskell:hlint - --refactor < sample.hs 

foo = x
```

**Comment by ndmitchell** [comment] 2015-11-24 09:43
It reproduced for me trivially on Windows. I guess a Windows vs Linux thing?

**Comment by mpickering** [comment] 2015-11-24 09:52
Maybe the problem is here?

```
runRefactoring :: FilePath -> FilePath -> FilePath -> String -> IO ExitCode
runRefactoring rpath fin hints opts =  do
  let args = [fin, "-v0"] ++ words opts ++ ["--refact-file", hints]
  (_, _, _, phand) <- createProcess $ proc rpath args
  hSetBuffering stdin LineBuffering
  hSetBuffering stdout LineBuffering
  -- Propagate the exit code from the spawn process
  waitForProcess phand
```

**Comment by ndmitchell** [comment] 2015-11-24 10:00
Looks like it - making the hSetBuffering stdin in a try fixes the issue. I guess after closing stdin, you can't set the LineBuffering on Windows, but you can on Linux.

**Comment by ndmitchell** [comment] 2015-11-24 11:31
I've made a new release, 1.9.25, which fixes this.

**Closed by ndmitchell** 2015-11-24 11:31 UTC

**Comment by expipiplus1** [comment] 2015-11-24 12:16
Thanks! That's fixed it.

@ndmitchell I'm running Linux though, so it can't just be a Windows vs Linux thing.

**Comment by mpickering** [comment] 2015-11-24 12:18
I am on OSX fwiw.

On Tue, Nov 24, 2015 at 12:16 PM, Joe Hermaszewski <notifications@github.com

**Comment by ndmitchell** [comment] 2015-11-24 12:33
Great, so I guess now it should work on all platforms!

**Comment by Drezil** [comment] 2015-12-05 19:52
Thing is when you use stdin on linux (e.g. cat foo.hs | hlint -) the socket gets closed before hlint gets called.
The release 1.9.25 fixes that - but you need HSE 1.17 for it to build. Problem is, that stack only has HSE 1.16 (and i quit tracking dependencies after that) and so it breaks with current Stack.

One solution (as long as this problem stands) would be to make a version 1.9.22.1 and push that to hackage. So you can just override what stack should install and it should install fine and even tell stack to use 1.9.22.1 in all future versions of lts and nightly until HSE 1.17 becomes available.

On my system i did a
`stack unpack hlint-1.9.22` and then edited the 2 lines needed for this change and did `stack install`.
Would be cool if you could just do `stack install hlint-1.9.22.1` to fix that (as it gets pulled from hackage then) as long as neither stack lts-*, nor stack nightly-* is up to the current build.

**Comment by ndmitchell** [comment] 2015-12-05 20:29
The fact that stack nightly doesn't yet have a recent HSE is a real pain, and as per the Stackage maintainers agreement, should have been fixed 10 days ago. I've pinged everyone again about it at https://github.com/fpco/stackage/issues/981

**Comment by ndmitchell** [comment] 2015-12-05 20:30
@Drezil, if it goes on too long, I'll make a 1.9.22.1, but that's a pain, and not something I like doing - I'd rather drag Stackage to the right versions as a first preference.

**Comment by ndmitchell** [comment] 2015-12-08 21:07
So it looks like Thursday/Friday we should be getting a stackage nightly that works, so not much point doing 1.9.22.1.

**Comment by ndmitchell** [comment] 2015-12-12 21:43
@Drezil, all released and in nightly now.
