### ISSUE TITLE
RecursiveDo extension not recognised

### ISSUE THREAD

**Issue by georgefst** [ndmitchell/hlint#681] opened 2019-06-20 10:22 UTC
I have the following .hlint.yaml:

    - arguments: [--color, --cpp-simple, -XQuasiQuotes, -XRecursiveDo]

    - extensions:
      - default: true
      - name: [PatternGuards, RecursiveDo, ViewPatterns]

But I get parse errors reported when using `mdo` (from the `RecursiveDo` extension) unless I put the language pragma in the source file.

As I understand it, explicitly telling hlint to use a particular extension _should_ enable that extension to be used across all files.

**Comment by ndmitchell** [comment] 2019-06-20 20:40
Thanks for the report! This will be a regression in newer HLint's which use the GHC parser.

@shayne-fletcher-da this is caused by GHC not taking the `ParseFlags.hseFlags.extensions` into account. Any extensions specified in that list should be added to the DynFlags, and similarly any explicitly disabled there should be removed. Do you want to take that?

Also, there should have been a test for this... My bad.

**Comment by shayne-fletcher-da** [comment] 2019-06-21 11:09
Absolutely @ndmitchell. I shall take care of it.

**Comment by ndmitchell** [comment] 2019-06-26 09:11
Fixed by #689

**Closed by ndmitchell** 2019-06-26 09:11 UTC
