### ISSUE TITLE
hlint parse error on * kind in QuasiQuotes

### ISSUE THREAD

**Issue by dspies-leapyear** [ndmitchell/hlint#569] opened 2018-12-15 16:01 UTC
I'm getting the hlint error: 

```
persistwrap/src/PersistWrap/TH.hs:17:28: Error: Parse error
Found:
    declareTables :: String -> Q [Dec]
    declareTables s = do
  >   argKind <- [t| Symbol -> * |]
      let n       = mkName s
          dataDec = DataD [] n [KindedTV (mkName "fk") argKind] Nothing [] []


1 hint
```

I think it has trouble with the kind-signature including `*`.

https://github.com/dspies-leapyear/persistwrap/blob/0d98f924208e2f4936e06c0b28ac5d223812c0fe/persistwrap/src/PersistWrap/TH.hs#L17

```
$ stack exec -- hlint --version
HLint v2.1.10, (C) Neil Mitchell 2006-2018
```

**Comment by ndmitchell** [comment] 2018-12-18 21:54
Thanks, this looks like a bug with the upstream library haskell-src-exts. I'll see how easy it is to fix.

**Comment by ndmitchell** [comment] 2020-03-15 20:35
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Closed by ndmitchell** 2020-03-15 20:35 UTC
Labels: depends-on-HSE
