### ISSUE TITLE
Incorrect "Unused LANGUAGE pragma" for TemplateHaskell

### ISSUE THREAD

**Issue by razvan-flavius-panda** [ndmitchell/hlint#741] opened 2019-08-18 03:19 UTC
To reproduce load this file: https://github.com/qfpl/hedgehog-fn/blob/master/example/Example.hs

Warning says that `{-# language TemplateHaskell #-}` is not needed.

If `{-# language TemplateHaskell #-}` is removed then `ghcmod` warns about:

    • Variable not in scope:
        ($$)
        :: (Group -> m0 Bool)
            -> Hedgehog.Internal.TH.TExpQ Group -> IO Bool
    • Perhaps you meant one of these:
        ‘$’ (imported from Prelude), ‘$!’ (imported from Prelude),
        ‘<$’ (imported from Prelude)

on the line:

    main = checkParallel $$discover

**Comment by ndmitchell** [comment] 2019-09-10 21:16
Thanks for the report. The root cause is that haskell-src-exts doesn't understand typed Template Haskell, so it parses the code as `a $$ b` with the infix operator `$$` rather than as a typed splice. If you switch `$$` for `$` then it correctly detects that TemplateHaskell is important.

The plan is to move away from haskell-src-exts to the GHC parser as part of #645, which hopefully fixes this issue.

**Comment by ndmitchell** [comment] 2020-03-15 20:43
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Closed by ndmitchell** 2020-03-15 20:43 UTC
Labels: depends-on-HSE
