### ISSUE TITLE
Update the version used by Code Climate

### ISSUE THREAD

**Issue by neongreen** [ndmitchell/hlint#733] opened 2019-08-11 13:59 UTC
The version they use currently is a year old.

https://hub.docker.com/r/codeclimate/codeclimate-hlint

**Comment by ndmitchell** [comment] 2019-08-11 18:13
I didn't write the code climate integration, I believe it was done by @pbrisbin.

**Comment by pbrisbin** [comment] 2019-08-14 18:26
:wave: hey there. I've lost touch with the Code Climate ecosystem since first submitting this engine... I've reached out to see what the current process is for getting it updated. Will report back soon, hopefully.

**Comment by neongreen** [comment] 2019-08-14 18:43
I DM'ed them on Twitter and they are planning to fork the engine to the codeclimate org and proceed from there. I haven't gotten any further replies from them since Monday though 🤔 

Pinging @davehenton.

**Comment by maxjacobson** [comment] 2019-08-14 19:49
Hi folks -

Just chatted with Dave. We had a misunderstanding and didn't realize that pbrisbin/codeclimate-hlint was [merged upstream](https://github.com/ndmitchell/hlint/pull/383) into this repo. So there's no need for us to fork that repo, or this one. We just need to update our internal system to point to a newer SHA in this repository. I've tried doing that, but I'm running into an error while building the image:

<details>
 <summary>Output</summary>

```text
$ git checkout v2.2.2
$ cc/build
Sending build context to Docker daemon  546.8kB
Step 1/33 : FROM fpco/stack-build:lts as builder
 ---> ed931fed86a2
Step 2/33 : MAINTAINER Pat Brisbin <pbrisbin@gmail.com>
 ---> Using cache
 ---> 87d8e219945e
Step 3/33 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 6919f044cbd5
Step 4/33 : ENV PATH /root/.local/bin:$PATH
 ---> Using cache
 ---> ec6959d3e4c5
Step 5/33 : RUN mkdir -p /src
 ---> Using cache
 ---> 6bf87eea97c6
Step 6/33 : WORKDIR /src
 ---> Using cache
 ---> 0d03bbb440c3
Step 7/33 : COPY hlint.cabal /src/
 ---> Using cache
 ---> 5bc20125511a
Step 8/33 : RUN stack init
 ---> Running in d58137fea410
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selecting the best among 16 snapshots...

* Partially matches lts-14.1
    ghc-lib-parser version 8.8.0.20190424 found
        - hlint requires ==8.8.0.20190723
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches nightly-2019-08-12
    ghc-lib-parser version 8.8.0.20190424 found
        - hlint requires ==8.8.0.20190723
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-13.30
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.20.3 found
        - hlint requires >=1.21 && <1.22
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-12.26
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.20.3 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util version 0.2.4 found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-11.22
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.20.2 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util version 0.2.3 found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-10.10
    extra version 1.6.4 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.19.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util version 0.2.2 found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-9.21
    extra version 1.5.3 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.18.2 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util version 0.2.1.2 found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-8.24
    aeson version 1.0.2.1 found
        - hlint requires >=1.1.2.0
    extra version 1.5.3 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.18.2 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-7.24
    aeson version 0.11.3.0 found
        - hlint requires >=1.1.2.0
    extra version 1.4.10 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.17.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-6.35
    aeson version 0.11.3.0 found
        - hlint requires >=1.1.2.0
    extra version 1.4.10 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.17.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-5.18
    aeson version 0.9.0.1 found
        - hlint requires >=1.1.2.0
    cpphs version 1.19.3 found
        - hlint requires >=1.20.1
    extra version 1.4.7 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.17.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-4.2
    aeson version 0.10.0.0 found
        - hlint requires >=1.1.2.0
    cpphs version 1.19.3 found
        - hlint requires >=1.20.1
    extra version 1.4.3 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.17.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-3.22
    aeson version 0.8.0.2 found
        - hlint requires >=1.1.2.0
    cpphs version 1.19.3 found
        - hlint requires >=1.20.1
    extra version 1.4.3 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.16.0.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-2.22
    aeson version 0.8.0.2 found
        - hlint requires >=1.1.2.0
    cpphs version 1.19.2 found
        - hlint requires >=1.20.1
    extra version 1.1 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.16.0.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    refact not found
        - hlint requires >=0.3
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-1.15
    aeson version 0.8.0.2 found
        - hlint requires >=1.1.2.0
    cpphs version 1.18.9 found
        - hlint requires >=1.20.1
    extra version 1.0.1 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.16.0.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    hscolour version 1.20.3 found
        - hlint requires >=1.21
    refact not found
        - hlint requires >=0.3
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

* Partially matches lts-0.7
    aeson version 0.8.0.2 found
        - hlint requires >=1.1.2.0
    cpphs version 1.18.6 found
        - hlint requires >=1.20.1
    extra version 1.0 found
        - hlint requires >=1.6.6
    ghc-lib-parser not found
        - hlint requires ==8.8.0.20190723
    haskell-src-exts version 1.16.0.1 found
        - hlint requires >=1.21 && <1.22
    haskell-src-exts-util not found
        - hlint requires >=0.2.5
    hscolour version 1.20.3 found
        - hlint requires >=1.21
    refact not found
        - hlint requires >=0.3
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

Selected resolver: lts-14.1
Resolver 'lts-14.1' does not have all the packages to match your requirements.
    ghc-lib-parser version 8.8.0.20190424 found
        - hlint requires ==8.8.0.20190723
    Using package flags:
        - hlint: FlagName "gpl" = True, FlagName "threaded" = True

This may be resolved by:
    - Using '--omit-packages' to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver

The command '/bin/sh -c stack init' returned a non-zero code: 1

```
</details>

Perhaps @neongreen or someone else can help us get the image building, and then we can update codeclimate.com to use that newer image. Thanks for your help :)

**Comment by neongreen** [comment] 2019-08-14 20:55
Looks like it won't work without adding a stack.yaml file to the repo – which will at some point go out of date unless @ndmitchell agrees to add `stack build` to the CI.

Or I can rewrite the Dockerfile to use Cabal.

**Comment by neongreen** [comment] 2019-08-14 21:54
See https://github.com/ndmitchell/hlint/pull/737.

**Comment by ndmitchell** [comment] 2019-08-17 16:48
I merged the related patch. What else needs doing?

**Comment by maxjacobson** [comment] 2019-08-19 16:45
Hi @ndmitchell thanks for merging. I can update codeclimate.com to use hlint based on what's currently on master. I see that it's several commits ahead of the latest official release, though: https://github.com/ndmitchell/hlint/compare/v2.2.2...4918ed15c20e2702f3681e9be0d6fcdebc0fb3cd . If I go ahead and do that, I'll probably update [our hlint docs](https://docs.codeclimate.com/docs/hlint) to say that we're using 2.2.2, although it'll be slightly ahead of 2.2.2. Do you anticipate any confusion emerging from that? If so, would it be appropriate to request that you cut a 2.2.3? Thank you!

**Comment by pbrisbin** [comment] 2019-08-19 17:03
Hey @maxjacobson, I have a few thoughts here, but no strong opinions. Hopefully what I'm about to say is useful and not just noise :)

As far as CC engines generally, I'm starting to like the approach of:

1. Making upstream CC-friendly

   The means some kind `--cc` flag to produce real CC Issues as JSON, as well as any changes to argument handling so CC an run the thing as need (e.g. single-file).

1. Make a *separate* wrapper repository

   That would be what is currently in this source tree as `./cc`. Putting this under `codeclimate-community` means you all can maintain those parts yourselves. Instead of copying in and compiling the raw, co-located source files, your `Dockerfile` would clone and checkout a tag or just install via (St|H)ackage.

I mention this because you may want to do (2) before (really, as a means of) resolving the versioning issue you raised.

That said, we could totally hold off on (2) for now and still use the approach of adding a `git reset --hard v2.2.2 && git cherry-pick ...` in the appropriate place in the build script, to get you all on an actual version, instead of _v2.2.2++_, or asking @ndmitchell to cut a release just for CC.

Either way, do let me know if I can be helpful here.

**Comment by maxjacobson** [comment] 2019-08-19 19:25
Thanks Pat - noise is helpful. The only reason I hesitate to suggest introducing a wrapper repository (which, I agree, does give us greater flexibility to release whichever version we like, as long as that version supports a `--cc` flag) was because this tool has already gone thru the process of having a wrapper repository which was separate, and then absorbing it. I'm happy to re-extract it if everyone's cool with that. We could make that repository and add some folks here as collaborators in case they want to help maintain it.

In the meantime, I like your idea of cherry-picking the fix on top of 2.2.2 to avoid releasing 2.22++. I'll take a crack at that today

**Comment by pbrisbin** [comment] 2019-08-19 20:00
>  because this tool has already gone thru the process of having a wrapper repository which was separate, and then absorbing it.

Ah yeah, that's the nuance: Previously, that separate repository was doing the work of **both** (1) and (2). In other words, it pulled in HLint the library, with no CC-friendly bits, and then re-exposed it as an Engine. That was not ideal, so we tried hard the other way. But after seeing this Issue run its course, I'm thinking (1) and (2) being both in the main upstream repository is also not ideal, and splitting it up so only (2) went to a wrapper repository could be the sweet spot.

**Comment by ndmitchell** [comment] 2019-08-19 21:15
I am unlikely to maintain the cc pieces, so I'm happy to host them in the HLint repo, but I'm really only providing hosting and some latency on merges. I'm OK with that, but equally OK if you want to pull it out.

I wouldn't overly worry about being 2.2.2+++, the changes are pretty minor. I can make a release for 2.2.3 later in the week.

**Comment by maxjacobson** [comment] 2019-08-19 21:18
Thanks y'all. FYI, for now, I've gone with the approach of checking out 2.2.2 and cherry-picking the CC-related fix, and releasing that, which is officially available via the CLI (just run `codeclimate engines:install` in your repository to pull down the latest) and via codeclimate.com. I think that works well for now.

In terms of a process for making sure that we keep the tool up-to-date over time, any hlint user is welcome to get in touch with us by opening an issue at https://github.com/codeclimate/codeclimate letting us know about the new version. Another option is to write in to our wonderful support team at https://codeclimate.com/help/new

**Comment by neongreen** [comment] 2019-08-19 21:26
> and via codeclimate.com. I think that works well for now.

You mean, it's already live on Codeclimate?

**Comment by maxjacobson** [comment] 2019-08-19 21:28
@neongreen  Yep, as of about 17:11 ET

**Closed** 2019-08-19 22:59 UTC

**Comment by pbrisbin** [comment] 2019-08-21 13:30
Since the update, we're seeing these Build Errors:

```
Couldn't find file: lint
engine: callProcess: hlint "lint" "--cc" "--datadir" "/opt/hlint" "--no-exit-code" "idp/" "ops/" ".github/" ".vscode/" "backend/jobs/" "backend/data-gen/" "backend/fancy-api/executables/" 
```

Does the new version have different usage (no `lint` sub-command)?

**Comment by neongreen** [comment] 2019-08-21 14:06
See #743.

**Comment by pbrisbin** [comment] 2019-08-21 14:07
Oh, you're quick! Thanks!

**Comment by maxjacobson** [comment] 2019-08-21 15:15
Ack, it appears I didn't do thorough enough QA before pushing out the release, sorry about that. I tried running `codeclimate analyze -e hlint` in the hlint repository, which does emit some issues without error for me, even now:

<details>
 <summary>Successful output</summary>


```
$ docker pull --quiet codeclimate/codeclimate-hlint
docker.io/codeclimate/codeclimate-hlint:latest

$ codeclimate analyze -e hlint
Starting analysis
Running hlint: Done!

== data/HLint_QuickCheck.hs (29 issues) ==
1: Use explicit module export list [hlint]
1: Avoid restricted extensions [hlint]
2: Avoid restricted extensions [hlint]
3: Avoid restricted extensions [hlint]
63: Avoid restricted function [hlint]
86: Avoid restricted function [hlint]
98: Avoid restricted function [hlint]
119: Redundant lambda [hlint]
119: Redundant bracket [hlint]
119: Redundant bracket [hlint]
119: Use elemIndex [hlint]
119: Use section [hlint]
121: Redundant bracket [hlint]
121: Use and [hlint]
121: Redundant bracket [hlint]
123: Redundant lambda [hlint]
123: Redundant bracket [hlint]
123: Use sqrt [hlint]
125: Redundant lambda [hlint]
125: Redundant bracket [hlint]
125: Redundant bracket [hlint]
127: Redundant lambda [hlint]
127: Redundant bracket [hlint]
127: Redundant bracket [hlint]
127: Use minimumBy [hlint]
129: Redundant lambda [hlint]
129: Redundant bracket [hlint]
129: Redundant $ [hlint]
129: Redundant bracket [hlint]

== data/Test.hs (3 issues) ==
33: Use concatMap [hlint]
40: Use second [hlint]
40: Use first [hlint]

== misc/HLint_NoDataFiles.hs (1 issue) ==
1: Avoid restricted extensions [hlint]

Analysis complete! Found 33 issues.
```
</details>

It def seems like you've identified a bug, but I'd appreciate if you could share context on how I can reproduce it

**Comment by pbrisbin** [comment] 2019-08-21 15:37
It also works for me in the hlint repo, but still fails in my project.

```console
% docker image ls codeclimate/codeclimate-hlint 
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
codeclimate/codeclimate-hlint   latest              7386b4282b2f        43 hours ago        233MB
```

Successful:

```console
% CODECLIMATE_DEBUG=1 codeclimate analyze -e hlint
Starting analysis
I, [2019-08-21T15:33:48.431316 #1]  INFO -- : starting engine hlint
D, [2019-08-21T15:33:48.433365 #1] DEBUG -- : /config.json content: {"enabled"=>true, "channel"=>"stable", "include_paths"=>[".gitignore", "src/", "data/hlint.1", "data/test-restrict.yaml", "data/HLint_QuickCheck.hs", "data/report_template.html", "data/hs-lint.el", "data/default.yaml", "data/hlint-restrict-extensions.yaml", "data/Shake.txt", "data/hlint.yaml", "data/Test.hs", "data/hlint.ghci", ".travis.yml", ".codeclimate.yml", ".weeder.yaml", "CHANGES.txt", "stack.yaml", "misc/", "hie.yaml", "travis.hs", "PULL_REQUEST_TEMPLATE.md", "tests/", "appveyor.yml", "Setup.hs", "hlint.cabal", ".dockerignore", ".hlint.yaml", "cc/", "LICENSE", ".ghci", "README.md"], "debug"=>"1"}
D, [2019-08-21T15:33:48.441333 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-hlint-stable-7d23030f-9a0a-4b7a-adbe-a56c66b7bbb8", "--cap-drop", "all", "--label", "com.codeclimate.label=d9495bf1-d6db-4d01-89ca-5a52f90591a4", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/patrick/code/ndmitchell/hlint:/code:ro", "--volume", "/tmp/cc/a36f2f54-0352-4ae0-b0ef-4518d9b06437:/config.json:ro", "--user", "9000:9000", "--memory", "1024000000", "codeclimate/codeclimate-hlint"]
D, [2019-08-21T15:33:52.217574 #1] DEBUG -- : engine stdout: {"location":{"path":"data/HLint_QuickCheck.hs","positions":{"begin":{"line":1,"column":1},"end":{"line":1,"column":1}}},"check_name":"HLint/UseExplicitModuleExportList","categories":["Style"],"content":{"body":"Found\n\n```\nmodule HLint_QuickCheck (\n        module HLint_QuickCheck, module X\n    ) where\n```\n\nPerhaps\n\n```\nmodule HLint_QuickCheck (\n         ... , module X\n    ) where\n```\n"},"remediation_points":250000,"type":"issue","description":"Use explicit module export list"}

--SNIP--
```

Error:

```console
% CODECLIMATE_DEBUG=1 codeclimate analyze -e hlint
Starting analysis
I, [2019-08-21T15:35:24.536923 #1]  INFO -- : starting engine hlint
D, [2019-08-21T15:35:33.686774 #1] DEBUG -- : /config.json content: {"enabled"=>true, "exclude_patterns"=>["haskell/backend/fancy-api/library/FrontRow/Api/Ela/Handler/Assignment.hs"], "checks"=>{"HLint/UnnecessaryHiding"=>{"enabled"=>false}}, "channel"=>"stable", "include_paths"=>[".gitignore", "docker-compose-apps.yml", "backend/school-report-generator/", "backend/.gitignore", "backend/core/", "backend/.weeder.yaml", "backend/jobs/", "backend/aws-xray-client/", "backend/stack.yaml", "backend/sendgrid-client/", "backend/fancy-api/.gitignore", "backend/fancy-api/config/", "backend/fancy-api/fancy-api.cabal", "backend/fancy-api/package.yaml", "backend/fancy-api/templates/", "backend/fancy-api/run-devel", "backend/fancy-api/log/", "backend/fancy-api/TESTREPORT", "backend/fancy-api/.stack-work/", "backend/fancy-api/tests/", "backend/fancy-api/doctest/", "backend/fancy-api/library/", "backend/fancy-api/.ghci", "backend/fancy-api/executables/", "backend/fancy-api/README.md", "backend/text-assets/", "backend/.stack-work-8.8/", "backend/.stack-work/", "backend/asana/", "backend/entities/", "backend/.stylish-haskell.yaml", "backend/.env.test", "backend/.env", "backend/stack.yaml.lock", "backend/.projections.json", "backend/roster-management/", "backend/snapshot.yaml", "backend/data-gen/", "backend/.stack-work-docs/", "backend/tags", "backend/frontrow-app/", "backend/Makefile", "backend/README.md", ".nvmrc", "build-assets-mac.command", "frontend/.gitignore", "frontend/console/app/", "frontend/console/.eslintrc.json", "frontend/console/.stylelintrc", "frontend/console/.flowconfig", "frontend/console/manifest.json", "frontend/console/index.html", "frontend/console/yarn.lock", "frontend/console/.eslintignore", "frontend/console/.cache/", "frontend/console/test/", "frontend/console/package.json", "frontend/console/css/", "frontend/console/scripts/", "frontend/.eslintrc.json", "frontend/school/.gitignore", "frontend/school/.prettierignore", "frontend/school/.eslintrc.json", "frontend/school/.stylelintrc", "frontend/school/.flowconfig", "frontend/school/.agignore", "frontend/school/manifest.json", "frontend/school/js/", "frontend/school/index.html", "frontend/school/yarn.lock", "frontend/school/.prettierrc", "frontend/school/.eslintignore", "frontend/school/.cache/", "frontend/school/test/", "frontend/school/package.json", "frontend/school/css/", "frontend/school/scripts/", "frontend/.stylelintrc", "frontend/student/.prettierignore", "frontend/student/.eslintrc.json", "frontend/student/.stylelintrc", "frontend/student/.flowconfig", "frontend/student/.agignore", "frontend/student/manifest.json", "frontend/student/js/", "frontend/student/index.html", "frontend/student/yarn.lock", "frontend/student/.eslintignore", "frontend/student/.cache/", "frontend/student/test/ela/", "frontend/student/test/district-assessments/", "frontend/student/test/jest-shim.js", "frontend/student/test/setup.js", "frontend/student/test/configure-test-framework.js", "frontend/student/test/common/", "frontend/student/test/math/", "frontend/student/package.json", "frontend/student/README.md", "frontend/student/css/", "frontend/student/scripts/", "frontend/.agignore", "frontend/prettify-staged-files.sh", "frontend/frontend-entities/.gitignore", "frontend/frontend-entities/.prettierignore", "frontend/frontend-entities/.eslintcache", "frontend/frontend-entities/config/", "frontend/frontend-entities/.eslintrc.json", "frontend/frontend-entities/.stylelintrc", "frontend/frontend-entities/.flowconfig", "frontend/frontend-entities/js/ela/", "frontend/frontend-entities/js/district-assessments/", "frontend/frontend-entities/js/roster/", "frontend/frontend-entities/js/units/", "frontend/frontend-entities/js/users/", "frontend/frontend-entities/js/common/mock/", "frontend/frontend-entities/js/common/helpers/date-helper.js", "frontend/frontend-entities/js/common/helpers/reading-session-status.js", "frontend/frontend-entities/js/common/helpers/common-helper.js", "frontend/frontend-entities/js/common/helpers/base/", "frontend/frontend-entities/js/common/helpers/products.js", "frontend/frontend-entities/js/common/helpers/non-empty.js", "frontend/frontend-entities/js/common/helpers/teacher-role.js", "frontend/frontend-entities/js/common/helpers/ajax-call-helper.js", "frontend/frontend-entities/js/common/helpers/parser/", "frontend/frontend-entities/js/common/helpers/keyboard.js", "frontend/frontend-entities/js/common/helpers/time-helpers.js", "frontend/frontend-entities/js/common/helpers/self-assigned.js", "frontend/frontend-entities/js/common/helpers/practice-modes.test.js", "frontend/frontend-entities/js/common/helpers/subjects.js", "frontend/frontend-entities/js/common/helpers/routers/", "frontend/frontend-entities/js/common/helpers/states.js", "frontend/frontend-entities/js/common/helpers/api-query-params.test.js", "frontend/frontend-entities/js/common/helpers/analytics/", "frontend/frontend-entities/js/common/helpers/ab-testing-helpers.js", "frontend/frontend-entities/js/common/helpers/test-helpers.js", "frontend/frontend-entities/js/common/helpers/bootstrap-table-helper.js", "frontend/frontend-entities/js/common/helpers/completion-status.js", "frontend/frontend-entities/js/common/helpers/generic-assignment-sessions-params.js", "frontend/frontend-entities/js/common/helpers/api-query-params.js", "frontend/frontend-entities/js/common/helpers/legacy-products.js", "frontend/frontend-entities/js/common/helpers/languages.js", "frontend/frontend-entities/js/common/helpers/practice-modes.js", "frontend/frontend-entities/js/common/helpers/touch-event-helper.js", "frontend/frontend-entities/js/common/helpers/bugsnag-helper.js", "frontend/frontend-entities/js/common/helpers/backbone.js", "frontend/frontend-entities/js/common/helpers/writing-session-status.js", "frontend/frontend-entities/js/common/helpers/grade-defaults.js", "frontend/frontend-entities/js/common/helpers/grade-defaults.test.js", "frontend/frontend-entities/js/common/helpers/common-bootstrap-table-helper.js", "frontend/frontend-entities/js/common/helpers/storage-helper.js", "frontend/frontend-entities/js/common/helpers/mock-demo.js", "frontend/frontend-entities/js/common/helpers/string-helper.js", "frontend/frontend-entities/js/common/helpers/time-helpers.test.js", "frontend/frontend-entities/js/common/helpers/asset-path-helper.js", "frontend/frontend-entities/js/common/helpers/mock.js", "frontend/frontend-entities/js/common/helpers/environment.js", "frontend/frontend-entities/js/common/helpers/split-io-helper.js", "frontend/frontend-entities/js/common/helpers/constants.js", "frontend/frontend-entities/js/common/helpers/common-api-helper.js", "frontend/frontend-entities/js/common/helpers/tts.js", "frontend/frontend-entities/js/common/components/", "frontend/frontend-entities/js/common/logic/", "frontend/frontend-entities/js/common/collections/", "frontend/frontend-entities/js/common/models/", "frontend/frontend-entities/js/math/", "frontend/frontend-entities/yarn.lock", "frontend/frontend-entities/.prettierrc", "frontend/frontend-entities/.eslintignore", "frontend/frontend-entities/test/", "frontend/frontend-entities/package.json", "frontend/frontend-entities/README.md", "frontend/frontend-entities/css/", "frontend/fr-materials/.eslintcache", "frontend/fr-materials/src/helpers/", "frontend/fr-materials/src/providers/", "frontend/fr-materials/src/components/checkbox/", "frontend/fr-materials/src/components/link/", "frontend/fr-materials/src/components/tabs/", "frontend/fr-materials/src/components/expandable-table/", "frontend/fr-materials/src/components/button-group/", "frontend/fr-materials/src/components/collapsible-container/", "frontend/fr-materials/src/components/tri-state-radio-button/", "frontend/fr-materials/src/components/expandable-container/", "frontend/fr-materials/src/components/spinner/", "frontend/fr-materials/src/components/label/", "frontend/fr-materials/src/components/common.scss", "frontend/fr-materials/src/components/expand-chevron-button/", "frontend/fr-materials/src/components/typography/", "frontend/fr-materials/src/components/tooltip/", "frontend/fr-materials/src/components/progress-bar/", "frontend/fr-materials/src/components/badge/", "frontend/fr-materials/src/components/container/", "frontend/fr-materials/src/components/dual-handle-slider/", "frontend/fr-materials/src/components/toggle/", "frontend/fr-materials/src/components/button/", "frontend/fr-materials/src/components/image-with-spinner/", "frontend/fr-materials/src/components/panel/", "frontend/fr-materials/.eslintrc.json", "frontend/fr-materials/.stylelintrc", "frontend/fr-materials/.flowconfig", "frontend/fr-materials/fonts/", "frontend/fr-materials/yarn.lock", "frontend/fr-materials/.eslintignore", "frontend/fr-materials/test/", "frontend/fr-materials/package.json", "frontend/fr-materials/css/", "frontend/classroom/.gitignore", "frontend/classroom/.prettierignore", "frontend/classroom/.eslintrc.json", "frontend/classroom/.stylelintrc", "frontend/classroom/.flowconfig", "frontend/classroom/.agignore", "frontend/classroom/manifest.json", "frontend/classroom/js/", "frontend/classroom/index.html", "frontend/classroom/yarn.lock", "frontend/classroom/.eslintignore", "frontend/classroom/.cache/", "frontend/classroom/test/ela/", "frontend/classroom/test/setup.js", "frontend/classroom/test/helpers/", "frontend/classroom/test/premium-access-mock.js", "frontend/classroom/test/configure-test-framework.js", "frontend/classroom/test/logic/", "frontend/classroom/test/common/", "frontend/classroom/test/math/", "frontend/classroom/package.json", "frontend/classroom/README.md", "frontend/classroom/css/", "frontend/classroom/scripts/", "frontend/webpack/helper/", "frontend/webpack/config/", "frontend/webpack/yarn.lock", "frontend/webpack/package.json", "frontend/webpack/scripts/", "frontend/eslint-config/", "frontend/.prettierrc", "frontend/Makefile", "frontend/README.md", "docker-compose-frontend-dev.yml", ".codeclimate.yml", "docker/faktory-pro/", "docker/services.yml", "docker/build-compose-file", "docker/base/", "docker/qa/", "docker/xray/", "docker/pgdump/", "docker/jobs/", "docker/fancy-api/.gitignore", "docker/fancy-api/run.sh", "docker/fancy-api/fancy-api", "docker/fancy-api/text-assets/", "docker/fancy-api/Dockerfile", "docker/fancy-api/get-artifacts.sh", "docker/snowflake-etl/", "docker/frontend-nginx/", "docker/text-assets-nginx/", "docker/ops/", "docker/demo-env-times/", "docker/jenkins/", "docker/Makefile", "docker/dd-agent/", "docker/common/", "docker/local-alb/", ".restyled.yaml", "text-assets/", "docker-compose-ops.yml", ".github/", "ops/.gitignore", "ops/requirements.txt", "ops/aws-scripts/", "ops/okta/", "ops/one-offs/", "ops/okta-aws-cli-login", "ops/fansible.sh", "ops/secrets/", "ops/haskell/", "ops/setup-dev-env.sh", "ops/nginx-localhost-cert/", "ops/venv/include/", "ops/venv/lib/", "ops/README.md", ".circleci/", "sql/", "docker-compose-all.yml", ".stylish-haskell.yaml", "docker-compose-backend-dev.yml", "add-math-question-ids.command", "docker-compose-sql.yml", ".env", "idp/", "brittany.yaml", "docker-compose.yml", ".hlint.yaml", "add-uuids.command", ".eslintignore", "Makefile", ".shake-text-assets/", "README.md", ".vscode/", ".editorconfig"], "debug"=>"1"}
D, [2019-08-21T15:35:33.695293 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-hlint-stable-4e5ec165-6969-4b77-b1f9-9adbc840c6e7", "--cap-drop", "all", "--label", "com.codeclimate.label=38823045-1d77-4896-a83d-6dd906d2b229", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/patrick/code/freckle/megarepo:/code:ro", "--volume", "/tmp/cc/61140b11-b7cd-44db-b02b-4d670689e992:/config.json:ro", "--user", "9000:9000", "--memory", "1024000000", "codeclimate/codeclimate-hlint"]
D, [2019-08-21T15:35:34.589259 #1] DEBUG -- : engine stderr: Couldn't find file: lint
D, [2019-08-21T15:35:34.599675 #1] DEBUG -- : engine stderr: engine: callProcess: hlint "lint" "--cc" "--datadir" "/opt/hlint" "--no-exit-code" "backend/school-report-generator/" --SNIP--
```

**Comment by pbrisbin** [comment] 2019-08-21 15:38
@maxjacobson I tried randomly in restyled-io/restyler and it fails there the same way. That project is open source so you should be able to repro there.

**Comment by neongreen** [comment] 2019-08-27 10:06
@maxjacobson can you grab the commit from https://github.com/ndmitchell/hlint/pull/743? This should fix Codeclimate for all repos containing a `.hlint.yaml` that specifies `arguments` (which is probably a lot of repos).
