### ISSUE TITLE
cpp appears to trip up hlint

### ISSUE THREAD

**Issue by bitemyapp** [ndmitchell/hlint#214] opened 2016-02-02 22:05 UTC
![screenshot from 2016-02-02 16-04-55](https://cloud.githubusercontent.com/assets/320177/12765966/c0fba508-c9c6-11e5-8ff4-cdad0c52e53b.png)

![screenshot from 2016-02-02 16-04-59](https://cloud.githubusercontent.com/assets/320177/12765970/c413d242-c9c6-11e5-9701-1e9f1eca6e64.png)

https://github.com/kazu-yamamoto/logger/blob/master/monad-logger/Control/Monad/Logger.hs

**Comment by ndmitchell** [comment] 2016-02-03 06:55
I think this is a dupe of #53. @malcolmwallace: did we get anywhere with that?

**Comment by DougBurke** [comment] 2016-03-19 17:23
I think it's fixed with cpphs 1.20.1 - see my response at https://github.com/ndmitchell/hlint/issues/53#issuecomment-193265800

**Comment by ndmitchell** [comment] 2016-03-21 21:36
@bitemyapp - if it does appear that cpphs 1.20.1 fixes it, I'll adjust the cabal bounds.

**Comment by ndmitchell** [comment] 2016-03-23 10:28
OK, I've added the minbound. @bitemyapp - please shout if cpphs doesn't fix it. I'll be making a new release in an hour or so.

**Closed by ndmitchell** 2016-03-23 10:28 UTC
