### ISSUE TITLE
Incorrect remove $ hint

### ISSUE THREAD

**Issue by neil-da** [ndmitchell/hlint#673] opened 2019-06-13 13:24 UTC
```
module Test where

mkDiag :: DynFlags -> T.Text -> ErrMsg -> Maybe FileDiagnostic
mkDiag dflags src e =
  case toDSeverity $ errMsgSeverity e of
    Nothing        -> Nothing
    Just bSeverity ->
      Just $ (toNormalizedFilePath $ srcSpanToFilename $ errMsgSpan e,)
        Diagnostic
        { _range    = srcSpanToRange $ errMsgSpan e
        , _severity = Just bSeverity
        , _source   = Just src
        , _message  = T.pack $ Out.showSDoc dflags (ErrUtils.pprLocErrMsg e)
        , _code     = Nothing
        , _relatedInformation = Nothing
        }
```

**Comment by ndmitchell** [comment] 2019-06-13 14:04
Simple case:

```
foo = (a $ b $ c d, )
```

The problem is HSE doesn't perform fixity resolution inside tuple sections, as per https://github.com/haskell-suite/haskell-src-exts/issues/434

**Comment by ndmitchell** [comment] 2020-03-15 20:40
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Closed by ndmitchell** 2020-03-15 20:40 UTC
Labels: depends-on-HSE
