### ISSUE TITLE
apply-refact library usage

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hlint#198] opened 2015-12-15 17:43 UTC
I am putting a plugin for hlint/apply-refact into haskell-ide-engine.

The standard way of doing it makes use of stdin/stdout, which is not available to a hie plugin.

I have got around this be exposing the constructor for `Suggestion` via https://github.com/alanz/hlint/commit/e32f4d3cf32d15003e54d4f42afae7bf06b50168, and making a library callable `applyRefactoring` in https://github.com/alanz/apply-refact/commit/ba98a2902e5333519e60d38803f30f82c44eaffc#diff-7c546fa1ddbbe07ca642c41df942b9e8R68

This has a signature of

```haskell
applyRefactorings :: Maybe (Int, Int) -> [(String, [Refactoring R.SrcSpan])] -> FilePath
                  -> IO String
```

At the moment this means hie needs a function 

```haskell
makeApplyRefact :: [Suggestion] -> [(String, [Refactoring R.SrcSpan])]
makeApplyRefact suggestions =
  map (\(Suggestion i) -> (show i, ideaRefactoring i)) suggestions
```

There are three ways of cleaning this up

1. Leave it as it is
2. Let `apply-refact` have `hlint` as a dependency, and change the signature to
      ```
      applyRefactorings :: Maybe (Int, Int) -> [Suggestion] -> FilePath
                        -> IO String
      ```

3. Modify `hlint` to have a version that returns [(String, [Refactoring R.SrcSpan])]

cc @mpickering

**Comment by ndmitchell** [comment] 2015-12-15 21:12
Hmm. I'd prefer HLint wasn't a dependency of refact, it seems wrong. My inclination is 3, without thinking about it sufficiently deeply yet.

On mobile only til Thur, but will give a better answer then.

**Comment by alanz** [comment] 2015-12-15 21:19
Ok, there's no rush. I do think I agree with you.

**Comment by ndmitchell** [comment] 2015-12-18 21:38
To get things in the latest HLint API, you should be modifying [`Language.Haskell.HLint3`](https://hackage.haskell.org/package/hlint-1.9.25/docs/Language-Haskell-HLint3.html), which looks substantially different from where your changes are. That module lets you obtain `Idea` values, and they have a field `ideaRefactoring :: [Refactoring SrcSpan]`, so I think you already have everything you want. Anything you see missing?

Note the docs on the other API's say: _WARNING: This module represents the old version of the HLint API. It will be deleted in favour of Language.Haskell.HLint3 in the next major version._

**Comment by alanz** [comment] 2015-12-18 21:55
The main reason I chose to use the original `hlint` function is that you can pass In the standard,  well-known command line flags. Users of hie are bound to want to be able to easily set options, which should be the same as those supplied supplied to the command line version.

**Comment by ndmitchell** [comment] 2015-12-18 23:00
The original API will be going away, so I have no plans to change it. I am open to having command line flag support in the new API, see #143.

**Comment by alanz** [comment] 2015-12-18 23:19
Yes, that would do it. Same motivation too, I see.

**Comment by ndmitchell** [comment] 2015-12-21 20:52
Closing as a dupe of #143.

**Closed by ndmitchell** 2015-12-21 20:52 UTC
